name: news
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.0-48.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  fluttertoast: ^8.0.7
  dio: ^4.0.3
  pretty_dio_logger: ^1.1.1
  cached_network_image: ^3.1.0+1
  modal_bottom_sheet: ^2.0.0
  url_launcher: ^6.0.15
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  photo_view: ^0.13.0
  flutter_svg: ^1.0.0
  timeago: ^3.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: InterBold
      fonts:
        - asset: assets/fonts/inter_bold.ttf
    - family: InterMedium
      fonts:
        - asset: assets/fonts/inter_medium.ttf
    - family: InterRegular
      fonts:
        - asset: assets/fonts/inter_regular.ttf